import {
  ArchitectureBought as ArchitectureBoughtEvent,
  ArchitectureUpgraded as ArchitectureUpgradedEvent,
  AutoGeneratedPeople as AutoGeneratedPeopleEvent,
  BaseClickUpgraded as BaseClickUpgradedEvent,
  ClickEvent as ClickEventEvent
} from "../generated/System/System"
import {
  ArchitectureBought,
  ArchitectureUpgraded,
  AutoGeneratedPeople,
  BaseClickUpgraded,
  ClickEvent
} from "../generated/schema"

export function handleArchitectureBought(event: ArchitectureBoughtEvent): void {
  let entity = new ArchitectureBought(
    event.transaction.hash.concatI32(event.logIndex.toI32())
  )
  entity.entityId = event.params.entityId
  entity.mold = event.params.mold
  entity.cost = event.params.cost

  entity.blockNumber = event.block.number
  entity.blockTimestamp = event.block.timestamp
  entity.transactionHash = event.transaction.hash

  entity.save()
}

export function handleArchitectureUpgraded(
  event: ArchitectureUpgradedEvent
): void {
  let entity = new ArchitectureUpgraded(
    event.transaction.hash.concatI32(event.logIndex.toI32())
  )
  entity.entityId = event.params.entityId
  entity.newLevel = event.params.newLevel
  entity.newAddPeople = event.params.newAddPeople

  entity.blockNumber = event.block.number
  entity.blockTimestamp = event.block.timestamp
  entity.transactionHash = event.transaction.hash

  entity.save()
}

export function handleAutoGeneratedPeople(
  event: AutoGeneratedPeopleEvent
): void {
  let entity = new AutoGeneratedPeople(
    event.transaction.hash.concatI32(event.logIndex.toI32())
  )
  entity.entityId = event.params.entityId
  entity.peopleGenerated = event.params.peopleGenerated
  entity.totalPeople = event.params.totalPeople

  entity.blockNumber = event.block.number
  entity.blockTimestamp = event.block.timestamp
  entity.transactionHash = event.transaction.hash

  entity.save()
}

export function handleBaseClickUpgraded(event: BaseClickUpgradedEvent): void {
  let entity = new BaseClickUpgraded(
    event.transaction.hash.concatI32(event.logIndex.toI32())
  )
  entity.entityId = event.params.entityId
  entity.newAddPeople = event.params.newAddPeople
  entity.newLevel = event.params.newLevel

  entity.blockNumber = event.block.number
  entity.blockTimestamp = event.block.timestamp
  entity.transactionHash = event.transaction.hash

  entity.save()
}

export function handleClickEvent(event: ClickEventEvent): void {
  let entity = new ClickEvent(
    event.transaction.hash.concatI32(event.logIndex.toI32())
  )
  entity.entityId = event.params.entityId
  entity.peopleAdded = event.params.peopleAdded
  entity.totalPeople = event.params.totalPeople

  entity.blockNumber = event.block.number
  entity.blockTimestamp = event.block.timestamp
  entity.transactionHash = event.transaction.hash

  entity.save()
}
